PACKAGE_NAME="linuxhost-wifi"
PACKAGE_VERSION="0.1.0"
BUILT_MODULE_NAME[0]="linuxhost_wifi"
DEST_MODULE_LOCATION[0]="/updates/dkms"
MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
CLEAN="make KDIR=/lib/modules/${kernelver}/build clean"
AUTOINSTALL="yes"
